/*/docking_server:
  ros__parameters:
    controller_frequency: 5.0 #Control frequency (Hz) for vision-control loop
    initial_perception_timeout: 5.0 #Timeout (s) to wait to obtain intial perception of the dock
    wait_charge_timeout: 5.0 #Timeout (s) to wait to see if charging starts after docking
    dock_approach_timeout: 30.0 #timeout (s) to attempt vision-control approach loop
    undock_linear_tolerance: 0.05 #Tolerance (m) to exit the undocking control loop at staging pose
    undock_angular_tolerance: 0.1 #Angular Tolerance (rad) to exist undocking loop at staging pose
    max_retries: 3 #Maximum number of retries to attempt
    base_frame: "base_link" #Robot's base frame for control law
    fixed_frame: "odom" #Fixed frame to use, recommended to be a smooth odometry frame not map
    dock_backwards: false #Whether the robot is docking with the dock forward or backward in motion
    dock_prestaging_tolerance: 1.0 #L2 distance in X,Y,Theta from the staging pose to bypass navigation
    # navigator_bt_xml: ""            #BT XML to use for Navigator, if non-default
    # navigator_bt_xml: "docking_server/behavior_trees/navigator_to_dock.xml"

    # Types of docks
    dock_plugins: ["jackal_dock"] #A set of dock plugins to load
    jackal_dock:
      plugin: "opennav_docking::SimpleChargingDock"
      docking_threshold: 0.05 #If not using stall detection, the pose threshold to the docking pose where isDocked() = true
      charging_threshold: 0.5 #Threshold of current in battery state above which isCharging() = true
      staging_x_offset: -0.2 #Staging pose offset forward (negative) of dock pose (m)
      staging_yaw_offset: 3.14 #Staging pose offset yaw (rad) of dock pose
      use_external_detection_pose: false #Whether to use external detection topic for dock or use the databases' pose
      use_battery_status: false #Whether to use the battery state message or isDocked() for isCharging()
      use_stall_detection: false #Whether or not to use stall detection for isDocked() or positional threshold

      # NOTE: the translation/rotation parameters do not work with PoseCorrectionNode, use the parameters defined in tags_36h11.yaml instead
      external_detection_timeout: 1.0 #Timeout at which if the newest detection update does not meet to fail
      external_detection_translation_x: -0.4 # X offset from detected pose for docking (m)
      external_detection_translation_y: 0.0 # Y offset from detected pose for docking (m)
      external_detection_rotation_roll: 1.57
      external_detection_rotation_pitch: 0.0
      external_detection_rotation_yaw: 0.0 #Yaw offset from detected pose for docking pose (rad)
      filter_coef: 0.1 #Dock external detection method filtering algorithm coefficient

    docks: ['charging_1','unloading_1'] #Instead of dock_database, the set of docks specified in the params file itself

    charging_1:
      type: "jackal_dock"
      frame: map
      # pose: [-0.13212, 6.39545, 0.0]
      pose: [1.075, 1.286, 1.57]   #1.075 2.286
    unloading_1:
      type: "jackal_dock"
      frame: map
      pose: [3.88763, 5.0, 1.57]

    # Sep. file of dock instances so config file can be used in multiple locations
    # this param will be overridden by the one in the launch file
    # dock_database: husky_nav_bringup/config/husky_dock_database.yaml

    controller:
      k_phi: 3.0
      k_delta: 2.0
      # v_linear_min: 0.15
      # v_linear_max: 0.15
      beta: 0.4
      lambda: 2.0
      v_linear_min: 0.2
      v_linear_max: 0.25
      v_angular_max: 0.3
      slowdown_radius: 0.25
      use_collision_detection: false
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0 #Time to look ahead for collisions (s).
      simulation_time_step: 0.1 #Time step for projections (s).
      dock_collision_threshold: 0.3 #Distance (m) from the dock pose to ignore collisions, i.e. the robot will not check for collisions within this distance from the dock pose, as the robot will make contact with the dock. Set to 0.0 when physical contact is not made with a dock.
