j100_0921/sensors/camera_0:
  stereolabs_zed:
    ros__parameters:
      use_sim_time: False
      # simulation.sim_enabled: False
      # simulation.sim_address: '127.0.0.1'
      # simulation.sim_port: 30000
      # svo.use_svo_timestamps: False
      # svo.svo_loop: False
      # svo.svo_realtime: False
      # svo.play_from_frame: 0
      general.camera_model: 'zed2i'
      general.camera_name: 'camera_0'
      general.camera_timeout_sec: 5
      general.camera_max_reconnect: 5
      general.camera_flip: False
      general.self_calib: False
      general.serial_number: 31947366
      general.pub_resolution: 'CUSTOM'  # The resolution used for output. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
      general.pub_downscale_factor: 2.0
      general.grab_resolution: 'HD720'
      general.grab_frame_rate: 30
      general.pub_frame_rate: 30.0
      general.enable_image_validity_check: 0
      general.gpu_id: -1
      general.optional_opencv_calibration_file: ''
      general.async_image_retrieval: False
      video.brightness: 4
      video.contrast: 4
      video.hue: 0
      video.saturation: 4
      video.sharpness: 4
      video.gamma: 8
      video.auto_exposure_gain: True
      video.exposure: 80
      video.gain: 80
      video.auto_whitebalance: True
      video.whitebalance_temperature: 42
      region_of_interest.automatic_roi: False
      region_of_interest.depth_far_threshold_meters: 2.5
      region_of_interest.image_height_ratio_cutoff: 0.5
      region_of_interest.apply_to_depth: True
      region_of_interest.apply_to_positional_tracking: True
      region_of_interest.apply_to_object_detection: True
      region_of_interest.apply_to_body_tracking: True
      region_of_interest.apply_to_spatial_mapping: True
      depth.depth_mode: 'NEURAL_LIGHT' # Matches the ZED SDK setting: 'NONE', 'PERFORMANCE', 'QUALITY', 'ULTRA', 'NEURAL', 'NEURAL_PLUS' - Note: if 'NONE' all the modules that requires depth extraction are disabled by default (Pos. Tracking, Obj. Detection, Mapping, ...)
      depth.depth_stabilization: 30
      depth.max_depth: 10.0
      depth.min_depth: 0.3
      depth.openni_depth_mode: False
      depth.point_cloud_freq: 10.0
      depth.point_cloud_res: 'REDUCED'
      depth.depth_confidence: 95
      depth.depth_texture_conf: 100
      depth.remove_saturated_areas: True
      pos_tracking.pos_tracking_enabled: True
      pos_tracking.pos_tracking_mode: 'GEN_2'
      pos_tracking.imu_fusion: True
      pos_tracking.publish_tf: False
      pos_tracking.publish_map_tf: False
      pos_tracking.map_frame: 'map'
      pos_tracking.odometry_frame: 'odom_zed'
      pos_tracking.area_memory_db_path: ''
      pos_tracking.area_memory: True
      pos_tracking.reset_odom_with_loop_closure: False
      pos_tracking.depth_min_range: 0.0
      pos_tracking.set_as_static: False
      pos_tracking.set_gravity_as_origin: True
      pos_tracking.floor_alignment: False
      pos_tracking.initial_base_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      pos_tracking.path_pub_rate: 2.0
      pos_tracking.path_max_count: -1
      pos_tracking.two_d_mode: True
      pos_tracking.fixed_z_value: 0.0
      pos_tracking.transform_time_offset: 0.0
      pos_tracking.reset_pose_with_svo_loop: True
      gnss_fusion.gnss_fusion_enabled: False
      gnss_fusion.gnss_fix_topic: '/j100_0921/sensors/gps_1/fix'
      gnss_fusion.gnss_zero_altitude: True
      gnss_fusion.h_covariance_mul: 1.0
      gnss_fusion.v_covariance_mul: 1.0
      gnss_fusion.publish_utm_tf: False
      gnss_fusion.broadcast_utm_transform_as_parent_frame: True
      gnss_fusion.enable_reinitialization: False
      gnss_fusion.enable_rolling_calibration: True
      gnss_fusion.enable_translation_uncertainty_target: False
      gnss_fusion.gnss_vio_reinit_threshold: 5.0
      gnss_fusion.target_translation_uncertainty: 0.1
      gnss_fusion.target_yaw_uncertainty: 0.01
      # gnss_antenna_position: [0.060, -0.181, 0.017]  #additional
      # gnss_initial_recalib_s: 1.0 #additional
      # gnss_min_yaw_accuracy: 1.0 #additional
      # gnss_min_translation_accuracy: 0.1 #additional
      mapping.mapping_enabled: False
      mapping.resolution: 0.05
      mapping.max_mapping_range: 5.0
      mapping.fused_pointcloud_freq: 1.0
      mapping.clicked_point_topic: '/clicked_point'
      mapping.pd_max_distance_threshold: 0.15
      mapping.pd_normal_similarity_threshold: 15.0
      sensors.publish_imu_tf: True
      sensors.sensors_image_sync: False
      sensors.sensors_pub_rate: 100.0
      object_detection.od_enabled: False
      object_detection.model: 'MULTI_CLASS_BOX_FAST'
      object_detection.custom_onnx_file: ''
      object_detection.custom_onnx_input_size: 512
      object_detection.custom_label_yaml: ''
      object_detection.allow_reduced_precision_inference: True
      object_detection.max_range: 20.0
      object_detection.confidence_threshold: 75.0
      object_detection.prediction_timeout: 0.5
      object_detection.enable_tracking: True
      object_detection.filtering_mode: 1
      object_detection.mc_people: True
      object_detection.mc_vehicle: True
      object_detection.mc_bag: True
      object_detection.mc_animal: True
      object_detection.mc_electronics: True
      object_detection.mc_fruit_vegetable: True
      object_detection.mc_sport: True
      body_tracking.bt_enabled: False
      body_tracking.model: 'HUMAN_BODY_MEDIUM'
      body_tracking.body_format: 'BODY_38'
      body_tracking.allow_reduced_precision_inference: False
      body_tracking.max_range: 20.0
      body_tracking.body_kp_selection: 'FULL'
      body_tracking.enable_body_fitting: False
      body_tracking.enable_tracking: True
      body_tracking.prediction_timeout_s: 0.5
      body_tracking.confidence_threshold: 50.0
      body_tracking.minimum_keypoints_threshold: 5
      stream_server.stream_enabled: False
      stream_server.codec: 'H264'
      stream_server.port: 30000
      stream_server.bitrate: 12500
      stream_server.gop_size: -1
      stream_server.adaptative_bitrate: False
      stream_server.chunk_size: 16084
      stream_server.target_framerate: 0
      advanced.thread_sched_policy: 'SCHED_BATCH'
      advanced.thread_grab_priority: 50
      advanced.thread_sensor_priority: 70
      advanced.thread_pointcloud_priority: 60
      debug.sdk_verbose: 1
      debug.debug_common: False
      debug.debug_sim: False
      debug.debug_video_depth: False
      debug.debug_camera_controls: False
      debug.debug_point_cloud: False
      debug.debug_positional_tracking: False
      debug.debug_gnss: False
      debug.debug_sensors: False
      debug.debug_mapping: False
      debug.debug_terrain_mapping: False
      debug.debug_object_detection: False
      debug.debug_body_tracking: False
      debug.debug_roi: False
      debug.debug_streaming: False
      debug.debug_advanced: False